###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "heybys",
  "password": "1q2w3e4r1!"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "heybys",
  "password": "1q2w3e4r1!"
}

> {%
client.global.set("accessToken", response.body.accessToken);
client.global.set("refreshToken", response.body.refreshToken);
 %}

###
GET http://localhost:8080/api/member
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/post
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/post/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST http://localhost:8080/api/post
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "post",
  "contents": "hello my name is Jero"
}
